#!/bin/bash
#
# Extract and run the rescue init packages/scripts...
#

case "$1" in
    start)
        shopt -s nullglob
        for file in /mnt/sysconfig/rescue/init*.tgz ; do
		TMPDIR=/tmp/init/`basename $file`
		echo "Extracting rescue init script $file..."
		mkdir -p "$TMPDIR"
		cd "$TMPDIR"
		tar -xzvf "$file"

		if [ -f "$TMPDIR/init.sh" ]; then
			echo "Starting rescue init script..."
			/bin/sh "$TMPDIR/init.sh"
		fi
        done
        for file in /mnt/sysconfig/rescue/init*.sh ; do
		echo "Starting rescue init script $file..."
		/bin/sh "$file"
	done
        shopt -u nullglob
        ;;
  stop)
        echo -n "Cleanup init temp files..."
        rm -rf /tmp/init
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?
